@startuml

package presentation {
     class GameView {}
     class KeyboardView {}
     class AnimationView {}
     class MainMenuView {}
     class StatsView {}
     class SettingsView {}

     class GameController {}
     class InputController {}
     class MenuController {}
     class AnimationController {}
 }
package domain {
    class Word {
    }
    class Letter {
    }
    class Guess {
    }
    abstract class WordleGameEngine {
    }
    class StandardWordle extends WordleGameEngine {
    }
    class GameState {
    }
    class WordValidator {
    }

}
package data {
}

@enduml
